// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUXtWb8H5KMhdFXWHgg6y4v4jywP669Y',
    appId: '1:1056116937101:android:eb1c3b17e714ba0d14adc4',
    messagingSenderId: '1056116937101',
    projectId: 'leisure-boat-controller',
    databaseURL: 'https://leisure-boat-controller-default-rtdb.firebaseio.com',
    storageBucket: 'leisure-boat-controller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T-XCTA9cUqDhcfuzZw9_yKOjW5-xapA',
    appId: '1:1056116937101:ios:b0c41f6ef40b6b7c14adc4',
    messagingSenderId: '1056116937101',
    projectId: 'leisure-boat-controller',
    databaseURL: 'https://leisure-boat-controller-default-rtdb.firebaseio.com',
    storageBucket: 'leisure-boat-controller.appspot.com',
    iosClientId: '1056116937101-dhg2c722nl4ru689f28m83oce9h4kc25.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensors',
  );
}
